### ISSUE TITLE
Fix Security Audit

### ISSUE THREAD

**Issue by c-thiel** [hansetag/iceberg-rest-server#4]
Currently the security Audit is failing:
https://github.com/hansetag/iceberg-rest-server/actions/runs/9081717741

**Comment by twuebi** [comment]
I looked a bit into this, it appears there's an issue with the rsa implementation used as transitive dependencies of some of our dependencies, from the looks it seems to be rather [long-standing](https://github.com/RustCrypto/RSA/issues/19#issuecomment-1822995643), there's [work](https://github.com/RustCrypto/RSA/pull/394) happening to resolve it but not much movement since April.

The other one is yaml-serde which has recently been marked as unmaintained, some background can be found [here](https://www.reddit.com/r/rust/comments/1bo5dle/we_lost_serdeyaml_whats_the_next_one/). 

Both don't seem to have any quick fixes, we may want to consider to ignore these advisories via a `audit.toml` (https://github.com/rustsec/rustsec/blob/main/cargo-audit/audit.toml.example) and monitor their status.

**Comment by c-thiel** [comment]
To get rid of the issue caused by `config`, we could also think about moving to `clap` instead
